const express = require('express');
const router = express.Router();
const { pool } = require('../db');

router.get('/:branchId/:date/:session', async (req, res) => {
  const { branchId, date, session } = req.params;
  try {
    const { rows } = await pool.query(`
      SELECT * FROM accessories_entries
      WHERE branch_id = $1 AND date = $2 AND session = $3
      ORDER BY accessory
    `, [branchId, date, session]);
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Always saves as 'evening'; morning is auto-generated by generateMorning
router.post('/', async (req, res) => {
  const { branch_id, date, entries } = req.body;
  if (!branch_id || !date || !Array.isArray(entries)) {
    return res.status(400).json({ error: 'branch_id, date, and entries array are required' });
  }

  const session = 'evening';
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query(
      `DELETE FROM accessories_entries WHERE branch_id = $1 AND date = $2 AND session = $3`,
      [branch_id, date, session]
    );
    for (const e of entries) {
      if (e.accessory && e.accessory.trim()) {
        await client.query(`
          INSERT INTO accessories_entries (branch_id, date, session, accessory, quantity)
          VALUES ($1, $2, $3, $4, $5)
          ON CONFLICT (branch_id, date, session, accessory)
          DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = NOW()
        `, [branch_id, date, session, e.accessory.trim(), e.quantity || 0]);
      }
    }
    await client.query('COMMIT');
    res.json({ success: true });
  } catch (err) {
    await client.query('ROLLBACK');
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

module.exports = router;
